CREATE TABLE IF NOT EXISTS members (
  username TEXT PRIMARY KEY,
  display_name TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'member' CHECK (role IN ('admin', 'member')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO members (username, display_name, role) VALUES
  ('Niwa', 'Niwa', 'admin'),
  ('Noah', 'Noah', 'admin'),
  ('Marie', 'Marie', 'member'),
  ('TomEliott', 'TomEliott', 'member'),
  ('Stecy', 'Stecy', 'member'),
  ('Luce', 'Luce', 'member'),
  ('Ayline', 'Ayline', 'member'),
  ('Ambre', 'Ambre', 'member'),
  ('Ezio', 'Ezio', 'member'),
  ('Thomas', 'Thomas', 'member'),
  ('Majda', 'Majda', 'member')
ON CONFLICT (username) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  role = EXCLUDED.role;

CREATE TABLE IF NOT EXISTS planning_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_date DATE NOT NULL,
  event_time TIME NOT NULL,
  title TEXT NOT NULL,
  location TEXT NOT NULL,
  created_by TEXT REFERENCES members(username) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (event_date, event_time, title, location)
);

INSERT INTO planning_events (event_date, event_time, title, location, created_by) VALUES
  ('2026-06-01', '18:30', 'Répétition chant', 'Salle principale', 'Noah'),
  ('2026-06-08', '19:00', 'Répétition chorégraphie', 'Studio', 'Noah'),
  ('2026-06-15', '20:00', 'Filage Alfred', 'Théâtre', 'Noah')
ON CONFLICT (event_date, event_time, title, location) DO NOTHING;
