ALTER TABLE members
ADD COLUMN IF NOT EXISTS age INTEGER;

ALTER TABLE members
ADD COLUMN IF NOT EXISTS display_role TEXT;

ALTER TABLE members
ADD COLUMN IF NOT EXISTS description TEXT;

ALTER TABLE members
ADD COLUMN IF NOT EXISTS gallery JSONB NOT NULL DEFAULT '[]'::jsonb;

ALTER TABLE members
ADD COLUMN IF NOT EXISTS display_order INTEGER;
